### PR TITLE
Style guide

### PR DESCRIPTION
**Pull request by srawulwar**
created style guide for js sdk

### CODE REVIEW

**Comment by techster10173** [comment]
[Add style guide to JS-SDK](https://trello.com/c/KdYMDLbl/16-add-style-guide-to-js-sdk)

**Review by dhruvarao11 — APPROVED** [review]
LGTM

**Review by sparshypop7 — APPROVED** [review]

**Comment by techster10173** [comment]
@srawulwar @vlasp we are going to be unable to merge this until typescript migration is merged in. Should we merge in typescript migration?

**Comment by techster10173** [comment]
Already merged into typescript-migration branch which is now merged into main

**Pull request closed without merging**
